# Generated by Django 5.1.3 on 2025-02-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_comment_post_alter_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(default="Default0216"),
            preserve_default=False,
        ),
    ]
