# Generated by Django 5.1.3 on 2025-02-23 10:58

from django.db import migrations, models


def set_default_description_for_category(apps, schema_editor):
    category_model = apps.get_model("blog", "Category")
    if category_model.objects.count() == 0:
        return

    for category in category_model.objects.all():
        category.description = f"This is {category.name} category(0223)."
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_tag_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(
            set_default_description_for_category,
            # U don't need another function when version go back.
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(),
        ),
    ]
